
# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    name: external-dns-operator
  name: external-dns-operator-metrics-monitor
  namespace: external-dns-operator
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      interval: 30s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  namespaceSelector:
    matchNames:
    - external-dns-operator
  selector:
    matchLabels:
      name: external-dns-operator
